### ISSUE TITLE
Trivial documentation error

### ISSUE THREAD

**Issue by skington** [DrHyde/perl-modules-Class-Mockable#11]
When talking about how you need to supply a *reference* to a coderef as output if you want the coderef to be called rather than returned, the documentation [says](https://github.com/DrHyde/perl-modules-Class-Mockable/blob/718ab2539bcdf5a2163acb92ca07265e46c875d9/lib/Class/Mock/Generic/InterfaceTester.pm#L147)

```
Note that it must be a reference to a code-ref, to distinguish from the case where
you really do want to return a code-ref. The code-ref supplied will be executed and
whatever it returns will be returned. If you want to return a reference to a code-ref
then you can perpetrate a mess like this:
    output => sub { \sub { ... } }
```

That last line should be
```
    output => \sub { \sub { ... } }
```

I couldn't be arsed forking the repository and opening a PR.

**Comment by DrHyde** [comment]
Thanks, fixed in 1.3002
